import { serve, type ServerType } from '@hono/node-server'
import { readFile } from 'node:fs/promises'
import { Server } from 'node:http'
import { join } from 'node:path'
import { checkCoverage, loadBank } from '../engine/content/bank.ts'
import { loadCorpus } from '../engine/corpus/corpus.ts'
import { AttemptStore } from '../engine/store/attempts.ts'
import { openHistoryDb } from '../engine/store/schema.ts'
import { VmStateStore } from '../engine/store/vm-state.ts'
import { loadTaskScripts } from '../engine/validate/harness.ts'
import { loadVmConfig } from '../engine/vm/config.ts'
import { chooseTransport } from '../engine/vm/select.ts'
import { VmController, VmrunTransport } from '../engine/vm/vmrun.ts'
import { createApp } from './app.ts'
import {
  allowedOriginsFor,
  coverageBanner,
  HOST,
  readPort,
  refuseToServe,
  serveOptions,
  VITE_DEV_PORT,
} from './config.ts'
import { createLabRuntime } from './lab.ts'
import { SessionStore } from './session.ts'
import { attachTerminal } from './terminal.ts'

// Wiring only. Everything with a decision in it lives in config.ts, where a
// test can reach it without this module's four side effects.
const PORT = readPort(process.env.RHCSA_PORT)
const CONTENT = process.env.RHCSA_CONTENT ?? 'content'
const SNAPSHOT = process.env.RHCSA_SNAPSHOT ?? 'clean'
// User history only, so it lives outside `content/`: the whole bank can be
// renumbered without touching it. `.gitignore` already covers `*.db`.
const DB = process.env.RHCSA_DB ?? '.rhcsa/history.db'
// The extracted book corpus, sibling to `content/` rather than inside it: it is
// generated by `scripts/extract-corpus.ts` from the two books, not authored.
const CORPUS = process.env.RHCSA_CORPUS ?? 'corpus'
const ALLOWED_ORIGINS = allowedOriginsFor(PORT, VITE_DEV_PORT)

const cfg = loadVmConfig(process.env)
const bank = await loadBank(CONTENT)

// Awaited at startup and deliberately unguarded, so a `ContentError` here kills the
// process exactly the way a bad bank does. That is the right severity: guided mode is
// the *only* way a student meets an objective for the first time (spec section 9.1),
// so a server that starts without a corpus is a server whose first-contact path
// silently 500s — and the alternative, degrading to "guided mode unavailable", is a
// study tool quietly missing a feature, which is the failure mode `loadCorpus`'s
// aggregate-and-throw design exists to prevent.
const corpus = await loadCorpus(CORPUS)

// `loadBank` validates each file against its schema; it does not resolve the
// references between them. `checkCoverage` does, and until now it ran only in
// `rhcsa coverage` — a command nothing invokes on the way here — so a task
// pointing at a concept id that does not exist served a hint ladder with rung 3
// quietly short and scored the attempt anyway. The rule itself is in `config.ts`,
// where a test can reach it; see `refuseToServe` for why `problems` refuses and
// the two gap lists only report.
const coverage = checkCoverage(bank)
const refusal = refuseToServe(coverage)
if (refusal !== undefined) {
  console.error(`rhcsa-trainer: ${refusal}`)
  process.exit(1)
}

const assertLib = await readFile(join(CONTENT, 'lib', 'assert.sh'), 'utf8')
const transport = await chooseTransport(cfg)
const controller = new VmController(cfg)

// One file, one handle, two stores. `openAttemptStore` / `openVmStateStore` each
// open a database of their own and are there for tests and for a caller that wants
// one of the two; here both stores read and write the same history file, and a second
// DatabaseSync on it would be a second connection with its own transaction state for
// no gain.
const historyDb = openHistoryDb({ path: DB })
const now = () => Date.now()

const app = createApp({
  bank,
  // `fallback` is the post-reboot-only second channel; see `GradeOptions.fallback`.
  // Constructed unconditionally because vmrun holds nothing open — it shells out
  // per call — and because `grade()` ignores it when it matches the chosen
  // transport, so the vmrun-only case costs nothing and needs no branch here.
  runtime: createLabRuntime({
    transport,
    controller,
    snapshot: SNAPSHOT,
    fallback: new VmrunTransport(cfg),
  }),
  sessions: new SessionStore(),
  assertLib,
  loadScripts: loadTaskScripts,
  now,
  attempts: new AttemptStore(historyDb, { now }),
  vmState: new VmStateStore(historyDb, { now }),
  corpus,
})

// The options come from `config.ts` so that `hostname` cannot be dropped here
// without a test noticing: this module has four import-time side effects and
// cannot be imported, so a test can only reach this line through `serveOptions`.
const server: ServerType = serve(serveOptions(app.fetch, PORT))

// `serve` returns `Server | Http2Server | Http2SecureServer`. Only the plain
// node:http server emits `upgrade` the way `attachTerminal` needs, and we never
// pass an http2 `createServer`, so this narrows rather than casts — a double cast
// through `unknown` here would be an admission that nobody checked.
if (!(server instanceof Server)) {
  throw new Error('expected a node:http server from serve(); the terminal cannot attach')
}
attachTerminal(server, { cfg, allowedOrigins: ALLOWED_ORIGINS })

console.log(`rhcsa-trainer api on http://${HOST}:${PORT} (transport: ${transport.kind})`)
console.log(
  `  ${bank.tasks.length} tasks, ${bank.concepts.length} concepts,` +
    ` ${corpus.items.length} corpus items, history in ${DB}`,
)
console.log(coverageBanner(coverage))
