import { ContentError } from '../content/errors.ts'

/**
 * Validation for one extracted corpus file.
 *
 * `corpus/` is `scripts/extract-corpus.ts`'s output: labs and exercises sliced
 * out of two `pdftotext -layout` dumps (spec section 2, Phase 0). Nothing in
 * `src/` read it before this module — it existed only as the extraction script's
 * test fixture — so the shape below is a description of what the four files
 * measurably contain today, not a schema the extractor was written against.
 *
 * **Why this is validated at all, given it is generated.** The corpus is
 * regenerated by hand, from two PDFs, on a machine where those PDFs may have
 * moved; the extractor's own heading and terminator regexes are heuristics over
 * layout text, and its comment says so. A regeneration that quietly loses a
 * chapter's headings produces a *shorter valid-looking JSON array*, and guided
 * mode built on an unvalidated loader would then offer the student nothing for
 * the objectives in that chapter with no error anywhere. Every rule here exists
 * to make that failure loud. The reused `ContentError` is the same aggregating,
 * file-and-field-naming error the `content/` loaders raise, for the same reason:
 * one run should report every problem in the file.
 */

/**
 * The two Cert Guide editions, as the directory names under `corpus/`.
 *
 * Keyed by the union rather than typed `readonly string[]`, following
 * `content/task.ts`'s `SCOPES`: a membership list that the compiler cannot check
 * against its own union is a list that silently stops matching when the union
 * grows.
 */
export type Edition = 'r9' | 'r10'
export type CorpusKind = 'lab' | 'exercise'

const EDITIONS: Record<Edition, true> = { r9: true, r10: true }
const KINDS: Record<CorpusKind, true> = { lab: true, exercise: true }

/**
 * Reading order for the two editions: RHCSA 9 first.
 *
 * Spec section 2: *"RHCSA 9 is primary — it matches the program table and the
 * targeted exam version."* This is written out rather than derived from
 * `Object.keys(EDITIONS)`, because that would rest a student-visible ordering on
 * object key order, and it is not `localeCompare` either — alphabetically `r10`
 * sorts *before* `r9` (`'1' < '9'`), which is why `corpus/signal.json` stores its
 * edition lists as `["r10", "r9"]`. Every ordering this module and
 * `guided/select.ts` produce uses this record, so the primary edition leads
 * everywhere.
 */
export const EDITION_ORDER: Record<Edition, number> = { r9: 0, r10: 1 }

export interface CorpusItem {
  /** `Lab 15.1` or `Exercise 15-2`. Stable across editions — that is the §14.4 pairing key. */
  id: string
  kind: CorpusKind
  chapter: number
  edition: Edition
  /** The item's body, first line included, exactly as extracted. */
  text: string
}

/**
 * The id shapes `findItems` builds, per kind. Both are anchored: the extractor
 * canonicalizes an id from its regex capture groups, so anything else in the file
 * means the file was not written by the extractor.
 */
const ID_SHAPES: Record<CorpusKind, RegExp> = {
  lab: /^Lab (\d{1,2})\.\d{1,2}$/,
  exercise: /^Exercise (\d{1,2})-\d{1,2}$/,
}

/**
 * Spec section 2: RHCSA 9 has 28 chapters, the higher of the two editions.
 *
 * Exported because `/api/guided/chapter/:n` validates against it, and a second
 * literal 28 in the server would be a bound that can drift from the one the
 * extractor enforces.
 */
export const MAX_CHAPTER = 28

function isEdition(v: unknown): v is Edition {
  return typeof v === 'string' && Object.hasOwn(EDITIONS, v)
}

function isKind(v: unknown): v is CorpusKind {
  return typeof v === 'string' && Object.hasOwn(KINDS, v)
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

export interface ExpectedFileShape {
  /** The edition the file's directory names. Every item must agree with it. */
  edition: Edition
  /** The kind the filename names. `labs.json` holding an exercise is a mis-split, not a variation. */
  kind: CorpusKind
}

/**
 * Parse and validate one `labs.json` / `exercises.json`.
 *
 * `expected` is what the *path* claims, and every item is checked against it.
 * That check is the point of taking the argument: `edition` and `kind` are
 * redundant fields inside a file whose directory and name already state both, and
 * redundant fields are exactly where a bad regeneration shows up first — the
 * extractor writes them from `filter((i) => i.kind === 'lab')` and a per-edition
 * loop, so a disagreement means the split or the loop broke.
 *
 * Rules, each with the measurement behind it (2026-09-13, over all 238 items):
 *
 * - **Non-empty array.** An empty file is the failure this whole module exists
 *   to refuse: guided mode over an empty exercise list offers nothing, silently.
 * - **`chapter` equals the chapter in the id.** The extractor derives both from
 *   the same capture group, so they cannot legitimately disagree. 238/238 agree.
 * - **`text` starts with the id.** Bodies are sliced from the heading line
 *   inclusive, so this holds for 238/238, and it is what lets `guided/select.ts`
 *   read a title off the first line instead of storing one.
 * - **An exercise's heading carries a title, a lab's does not.** Measured: all
 *   180 exercise headings have text after the id (`Exercise 15-1 Creating a
 *   Physical Volume`), all 58 lab headings are bare (`Lab 15.1`), which is why
 *   this rule is per kind. It does *not* catch the extractor's known worst case,
 *   a body that lost the dedupe race and kept a one-line table-of-contents entry
 *   — those have titles too. `test/guided/corpus-real.test.ts` covers that from
 *   the other side, by asserting every exercise parses into at least one step.
 * - **No duplicate ids within a file.** `findItems` dedupes by id, so a repeat
 *   means two files were concatenated or an edition loop ran twice.
 */
export function parseCorpusItems(
  raw: unknown,
  where: string,
  expected: ExpectedFileShape,
): CorpusItem[] {
  const problems: string[] = []

  if (!Array.isArray(raw)) {
    throw new ContentError(where, ['file must contain a JSON array of corpus items'])
  }
  if (raw.length === 0) {
    // Thrown alone, before the per-item loop, because there is nothing else to
    // say about an empty file and the message should not be diluted.
    throw new ContentError(where, [
      'file contains no items; re-run scripts/extract-corpus.ts rather than shipping an empty corpus',
    ])
  }

  const items: CorpusItem[] = []
  const seen = new Set<string>()
  const shape = ID_SHAPES[expected.kind]

  for (const [i, entry] of raw.entries()) {
    if (!isRecord(entry)) {
      problems.push(`items[${i}] must be a JSON object`)
      continue
    }

    const at = `items[${i}]`
    const idMatch = typeof entry.id === 'string' ? shape.exec(entry.id) : null
    const id = idMatch === null ? '' : (entry.id as string)
    if (!id) {
      problems.push(
        `${at}.id must be a ${expected.kind} id matching ${String(shape)}, got ${JSON.stringify(entry.id)}`,
      )
    } else if (seen.has(id)) {
      problems.push(`${at}: duplicate id ${id}`)
    }
    if (id) seen.add(id)

    if (!isKind(entry.kind) || entry.kind !== expected.kind) {
      problems.push(`${at}.kind must be "${expected.kind}", got ${JSON.stringify(entry.kind)}`)
    }

    if (!isEdition(entry.edition) || entry.edition !== expected.edition) {
      problems.push(
        `${at}.edition must be "${expected.edition}", got ${JSON.stringify(entry.edition)}`,
      )
    }

    const chapter = entry.chapter
    const validChapter =
      typeof chapter === 'number' && Number.isInteger(chapter) && chapter >= 1 && chapter <= MAX_CHAPTER
    if (!validChapter) {
      problems.push(`${at}.chapter must be an integer 1-${MAX_CHAPTER}, got ${JSON.stringify(chapter)}`)
    }
    // Only comparable once both sides parsed; an id that failed its shape has no
    // chapter to compare against and has already been reported.
    const idChapter = idMatch?.[1] === undefined ? undefined : Number(idMatch[1])
    if (validChapter && idChapter !== undefined && idChapter !== chapter) {
      problems.push(`${at}.chapter is ${chapter} but its id ${id} says chapter ${idChapter}`)
    }

    const text = typeof entry.text === 'string' ? entry.text : ''
    if (typeof entry.text !== 'string' || entry.text.trim() === '') {
      problems.push(`${at}.text must be a non-empty string`)
    } else if (id && !text.startsWith(id)) {
      problems.push(
        `${at}.text must begin with the heading line ${JSON.stringify(id)}, got ${JSON.stringify(text.slice(0, 40))}`,
      )
    } else if (id && expected.kind === 'exercise' && headingTitle(id, text) === '') {
      problems.push(`${at}: exercise ${id} has no title after its id on the heading line`)
    }

    items.push({
      id,
      kind: expected.kind,
      chapter: validChapter ? chapter : 0,
      edition: expected.edition,
      text,
    })
  }

  if (problems.length > 0) throw new ContentError(where, problems)
  return items
}

/**
 * The heading line's text after the id — the item's title, when it has one.
 *
 * Exported because `guided/select.ts` reads it off the item rather than the
 * loader storing a fifth field; the invariant that makes that safe (`text` starts
 * with `id`) is enforced above.
 *
 * The leading colon is dropped because the book sometimes prints one and
 * sometimes does not, and a title rendered as *": Using Systemd Timers"* is a
 * typo on the student's screen. Measured 2026-09-13: 2 of the 180 exercise
 * instances are affected, both editions' `Exercise 12-1`, which prints
 * *"Exercise 12-1: Using Systemd Timers"*; the other 178 print no punctuation
 * between the id and the title. Only a colon is stripped, and only at the front —
 * `Exercise 13-4 Changing rsyslog.conf Rules` and `Exercise 19-4 Using if ...
 * then ... else` show that punctuation elsewhere in a title is the title.
 *
 * This does not weaken the empty-title rule above: dropping a colon cannot turn a
 * titled heading into an untitled one, because a heading whose whole remainder is
 * `:` has no title either way.
 */
export function headingTitle(id: string, text: string): string {
  const firstLine = text.split('\n', 1)[0] ?? ''
  return firstLine.slice(id.length).replace(/^\s*:/, '').trim()
}

/**
 * `corpus/signal.json`: item id to the editions containing it.
 *
 * Section 14.4.1's weight signal. Present in both editions means durable core
 * RHCSA material; present in one means version-specific. Returned as a `Map`
 * with the edition list reordered primary-first (see `EDITION_ORDER`), because
 * the file stores it alphabetically, which puts `r10` first.
 *
 * The values are validated but *not* cross-checked against the item files here —
 * that check needs both sides and lives in `loadCorpus`.
 */
export function parseSignal(raw: unknown, where: string): Map<string, Edition[]> {
  if (!isRecord(raw)) {
    throw new ContentError(where, ['file must contain a JSON object of id to edition list'])
  }

  const problems: string[] = []
  const out = new Map<string, Edition[]>()

  const ids = Object.keys(raw)
  if (ids.length === 0) {
    throw new ContentError(where, [
      'file records no items; re-run scripts/extract-corpus.ts rather than shipping an empty weight signal',
    ])
  }

  for (const id of ids) {
    const value = raw[id]
    if (!Array.isArray(value) || value.length === 0) {
      problems.push(`${id} must map to a non-empty array of edition tags`)
      continue
    }
    const editions: Edition[] = []
    let bad = false
    for (const e of value) {
      if (!isEdition(e)) {
        problems.push(`${id} lists an unknown edition ${JSON.stringify(e)}`)
        bad = true
        continue
      }
      if (editions.includes(e)) {
        problems.push(`${id} lists edition ${e} twice`)
        bad = true
        continue
      }
      editions.push(e)
    }
    if (bad) continue
    out.set(id, editions.sort((a, b) => EDITION_ORDER[a] - EDITION_ORDER[b]))
  }

  if (problems.length > 0) throw new ContentError(where, problems)
  return out
}
