#!/usr/bin/env bash
# Grader for net/044-hostname-and-name-resolution.
#
# READ-ONLY. Changes nothing on the guest. The exit code is ignored; only the
# JSONL the checkpoint helpers write to stdout is read. content/lib/assert.sh is
# prepended by loadTaskScripts, so those helpers are already in scope - do not
# source it. (Their names are left unspelled in every comment in this file on
# purpose: the id extractor documented in docs/r1-findings.md reads comment text
# as readily as code, so prose that looks like a call invents a checkpoint.)
#
# ---------------------------------------------------------------------------
# Why the two resolver checkpoints grade CONFIGURATION and not effect.
#
# The whole point of `nmcli connection modify ... ipv4.dns` is that it writes the
# profile and applies nothing; the setting reaches /etc/resolv.conf when the
# connection next activates. The obvious grader would therefore ask for the
# reactivation and then read /etc/resolv.conf. This one deliberately does not, and
# it is the central design decision in this task.
#
# `nmcli connection up` on the profile that owns the only NIC re-runs the
# activation from scratch: the device is deconfigured and reconfigured, which for
# a DHCP profile means a fresh lease and, for the duration, no address. This lab
# grades over ssh on that interface (task.yaml declares `transport: ssh`), so an
# answer that reactivates the connection can cut the channel the grader arrives
# on. That is not a failing checkpoint, it is an unrunnable task - the harness
# gets no JSONL at all and every checkpoint reads as missing. The evidence for
# treating it as real rather than theoretical is not one source but four:
#
#   - the r9 book opens exercise 8-3, which is nothing but nmcli connection work,
#     with "Run this exercise from a console session, not using an SSH
#     connection";
#   - exercise 8-4 sets ipv4.dns with `con mod` and then needs a separate step 6,
#     "After changing connection properties, you need to activate them" - so the
#     write and the apply are two distinct acts and only the second is dangerous;
#   - docs/offline-mode.md rejected `ipv4.never-default` for this trainer for
#     exactly this reason: it "bounces the connection (killing ssh mid-command)";
#   - the one task in this bank whose anti-solution does reactivate a connection,
#     content/tasks/troubleshooting/028-restore-remote-access, declares
#     `transport: vmrun` and is graded through vmtoolsd, which does not care.
#
# So the prompt asks for the setting to be RECORDED in the profile, says in as
# many words that it does not have to take effect yet, and forbids reactivation;
# and dns-nameserver and dns-search read the saved profile. Two witnesses, either
# sufficient: nmcli's own view of the profile, and the keyfile under
# /etc/NetworkManager/system-connections. Both are persistent by construction,
# which is what makes these checkpoints meaningful in verdict B - the reboot
# activates the profile, so a setting that is really there is also in effect
# afterwards, and one that was faked into /etc/resolv.conf by hand is gone.
#
# The cost of the decision is honest and worth stating: this grader cannot tell a
# student who recorded the setting and left it inert from one who recorded it and
# activated it from the console. Both are correct answers to the prompt as
# written, so there is nothing to distinguish. What it can and does tell is the
# student who edited /etc/resolv.conf instead - that file is generated by
# NetworkManager, carries a "Generated by NetworkManager" banner, and is rewritten
# on the next activation, so it is a wrong answer even though it looks right
# today. antisolutions/02 is that fixture.
#
# /etc/resolv.conf is therefore never read as evidence FOR anything here. It is
# read once, into a detail string, so a student who took that route can see their
# own work quoted back at them next to the fail.
# ---------------------------------------------------------------------------
# Why the host's own name is graded out of /etc/hosts and the peer's with getent.
#
# nss-myhostname. /etc/nsswitch.conf on this guest reads `hosts: files dns
# myhostname` (verified on RHEL 9.8), and nss-myhostname answers for whatever the
# local hostname currently is, with the machine's own interface addresses. So
# `getent hosts app1.lab.example.com` starts succeeding the moment the hostname is
# set, with nothing added to any file - which would make a getent-based check on
# the host's own name pass for free and grade nothing. The self-hosts-entry
# checkpoint therefore parses /etc/hosts, where the answer has to be written down.
# getent's answer is reported in the detail as corroboration, never as the
# criterion.
#
# The peer name is the opposite case: nss-myhostname cannot claim
# filer1.lab.example.com, nothing else on an offline guest can either, and a
# student may legitimately spell the entry in any of several layouts (one line
# with an alias, two lines, extra whitespace). So that one is graded by asking the
# resolver, which accepts every correct spelling and no incorrect one.
# ---------------------------------------------------------------------------
#
# Checkpoints that must fail before the student does anything. Everything not
# listed is an invariant and must PASS from the start.
# baseline-fail: hostname-live, hostname-static, self-hosts-entry, peer-resolves, dns-nameserver, dns-search
#
# The interface, its address, its profile and that profile's addressing method are
# all still as the lab left them. This is an invariant and it is asserted below,
# but no fixture in this task probes it, and that is deliberate rather than an
# oversight: an anti-solution that renumbered or downed the only NIC would not
# fail a checkpoint, it would sever the ssh channel the grader arrives on and
# produce no verdict at all. The same reasoning as `var-intact` in
# content/tasks/storage/014-grow-home-lv/grade.sh and `student-intact` in
# content/tasks/troubleshooting/028-restore-remote-access/grade.sh: the id exists
# so that a student who wanders into the addressing while chasing the resolver
# settings is told which of their two problems is which.
# unprobed-invariant: network-intact
set -uo pipefail

# Spelled identically in setup.sh.
FQDN=app1.lab.example.com
SHORT=app1
PEER_FQDN=filer1.lab.example.com
PEER_SHORT=filer1
PEER_ADDR=192.0.2.40
DNS_SERVER=192.168.70.2
DNS_SEARCH=lab.example.com

HOSTS=/etc/hosts
HOSTNAME_FILE=/etc/hostname
RESOLV=/etc/resolv.conf
STAMP=/var/lib/rhcsa-lab/044-net-facts

# --- fail-closed preamble -------------------------------------------------
# Everything below needs the tools this reads with and the facts setup.sh
# recorded. If either is missing, every checkpoint fails with the same reason
# rather than some of them passing vacuously - a name that resolves nowhere and a
# name this script could not look up must not read the same way.
#
# Modelled on storage/014's preamble, and needed here for a sharper reason than
# tidiness: three of the eight checkpoints below are satisfied by finding
# something, and the other five by NOT finding something. Negative checks are
# exactly the shape that passes when the probe itself is broken.
bail() {
  local why=$1
  ck_fail hostname-live "the running system's name is $FQDN" "$why"
  ck_fail hostname-static "the name $FQDN survives a reboot" "$why"
  ck_fail self-hosts-entry "$HOSTS maps this host's own address to $FQDN and $SHORT" "$why"
  ck_fail peer-resolves "$PEER_FQDN and $PEER_SHORT resolve to $PEER_ADDR" "$why"
  ck_fail dns-nameserver "the connection profile records $DNS_SERVER as its DNS server" "$why"
  ck_fail dns-search "the connection profile records $DNS_SEARCH as its DNS search domain" "$why"
  ck_fail hosts-localhost "$HOSTS still maps 127.0.0.1 and ::1 to localhost" "$why"
  ck_fail network-intact "the interface, its address and its connection profile are unchanged" "$why"
  exit 0
}

for t in uname hostnamectl getent ip awk nmcli; do
  command -v "$t" >/dev/null \
    || bail "$t is missing from this guest, so nothing in this task can be measured; this is a broken image, not a wrong answer"
done

sudo test -r "$HOSTS" \
  || bail "$HOSTS cannot be read even as root, so no name resolution claim can be checked"

# The facts about the network setup.sh recorded before the student touched
# anything. Read as student - setup.sh leaves the file mode 0644 for this - and
# read with awk, which reads to EOF, so this is not the `producer | grep -q`
# SIGPIPE trap content/lib/assert.sh documents.
fact() { awk -F= -v k="$1" '$1 == k { v = $2 } END { print v }' "$STAMP" 2>/dev/null; }
[[ -r $STAMP ]] \
  || bail "$STAMP is missing or unreadable, so this grader does not know which interface or which connection profile the lab handed over; run setup.sh for this task"
STAMP_DEV=$(fact dev)
STAMP_ADDR=$(fact addr)
STAMP_UUID=$(fact uuid)
STAMP_METHOD=$(fact method)
[[ -n $STAMP_DEV && -n $STAMP_ADDR && -n $STAMP_UUID && -n $STAMP_METHOD ]] \
  || bail "$STAMP is incomplete (dev='$STAMP_DEV' addr='$STAMP_ADDR' uuid='$STAMP_UUID' method='$STAMP_METHOD'); re-run setup.sh for this task"

# The live view, derived from the ADDRESS rather than from the default route: in
# drill and exam modes the trainer drops the guest's default route
# (docs/offline-mode.md), so `ip route get` and `ip -o route show default` are
# empty for exactly the sessions a student studies in, and a grader that derived
# the device that way would report a broken network for every one of them.
read -r LIVE_DEV LIVE_CIDR < <(ip -4 -o addr show scope global 2>/dev/null |
  awk '$2 != "lo" && !seen { print $2, $4; seen = 1 }')
LIVE_DEV=${LIVE_DEV:-}
LIVE_ADDR=${LIVE_CIDR%/*}
LIVE_ADDR=${LIVE_ADDR:-}

# --- 1 and 2. the name ----------------------------------------------------
# Two checkpoints, because running-name and name-after-a-reboot are independent
# properties and the difference between them is the objective. `hostname app1...`
# sets the first and not the second; `hostnamectl set-hostname app1...` sets both;
# writing /etc/hostname and then `hostname app1...` also sets both. Nothing
# visible in a shell prompt distinguishes the first from the others, which is what
# makes this the cleanest persistence pair in the bank -
# antisolutions/01-transient-hostname-only.sh passes hostname-live in verdict A
# and regresses in verdict B.
#
# uname -n rather than the `hostname` command: it is the kernel's own answer via
# uname(2), so it cannot be affected by anything in /etc, and it is what every
# program that calls gethostname() sees. Compared as a whole string - a substring
# test would accept app1.lab.example.com.attacker.test.
live_name=$(uname -n 2>/dev/null)
if [[ $live_name == "$FQDN" ]]; then
  ck_pass hostname-live "the running system's name is $FQDN" "uname -n reports $live_name"
else
  ck_fail hostname-live "the running system's name is $FQDN" \
    "uname -n reports '${live_name:-nothing}'. This is the name the running kernel holds; note that it can be set on its own, without being written down anywhere, in which case it is gone after a reboot"
fi

# Two witnesses, either sufficient, because there are two documented ways to make
# a hostname persistent and both are correct answers: `hostnamectl set-hostname`
# (which writes the file for you) and writing /etc/hostname by hand. The file is
# read directly as well as through hostnamed because systemd-hostnamed is
# bus-activated and a grader that trusted only its answer would be trusting a
# cache to have noticed a file somebody edited. Read under sudo because a student
# may have created the file with a restrictive mode.
static_file=$(sudo awk '
  /^[[:space:]]*#/ { next }
  /^[[:space:]]*$/ { next }
  { gsub(/^[[:space:]]+|[[:space:]]+$/, ""); print; exit }' "$HOSTNAME_FILE" 2>/dev/null)
static_bus=$(hostnamectl --static 2>/dev/null)
if [[ $static_file == "$FQDN" || $static_bus == "$FQDN" ]]; then
  ck_pass hostname-static "the name $FQDN survives a reboot" \
    "$HOSTNAME_FILE holds '${static_file:-nothing}', hostnamectl reports the static name as '${static_bus:-nothing}'"
else
  ck_fail hostname-static "the name $FQDN survives a reboot" \
    "$HOSTNAME_FILE holds '${static_file:-nothing}' and hostnamectl reports the static name as '${static_bus:-nothing}'. A hostname is only persistent if it is written to $HOSTNAME_FILE; the running name alone is not"
fi

# --- 3. this host's own name in the hosts file ----------------------------
# Every name on the line for a given address, one per line. The comment is
# stripped first, because `192.0.2.40 # filer1.lab.example.com` names nothing, and
# NF >= 2 skips an address with no names after it. awk reads to EOF - not the
# SIGPIPE trap.
hosts_names_for() {
  sudo awk -v a="$1" '
    { sub(/#.*/, "") }
    NF >= 2 && $1 == a { for (i = 2; i <= NF; i++) print $i }' "$HOSTS" 2>/dev/null
}
# Whole-line equality against a newline-separated list. Never a substring test: it
# has to reject `app12` for `app1` and `lab.example.com` for `app1.lab.example.com`.
has_name() { printf '%s\n' "$1" | awk -v w="$2" '$0 == w { hit = 1 } END { exit hit ? 0 : 1 }'; }

# The same list flattened for a detail string, as `a b c` or `none`.
names_summary() {
  local flat
  flat=$(printf '%s' "$(hosts_names_for "$1")" | tr '\n' ' ' | cut -c1-120)
  flat=${flat%% }
  printf '%s' "${flat:-none}"
}

# The address the entry has to name. The live one is what the prompt asks for
# ("the IPv4 address the host's interface currently has"), and the stamped one is
# accepted as well when the two differ, because they can only differ for a reason
# outside the student's control: this guest is a DHCP client, and a lease that
# renews to a different address between setup and grading - or across verdict B's
# reboot - would otherwise turn a correct answer into a failure. Both are
# reported in the detail so the discrepancy is never silent.
addr_candidates=()
[[ -n $LIVE_ADDR ]] && addr_candidates+=("$LIVE_ADDR")
[[ -n $STAMP_ADDR && $STAMP_ADDR != "$LIVE_ADDR" ]] && addr_candidates+=("$STAMP_ADDR")

self_hit=""
for a in ${addr_candidates+"${addr_candidates[@]}"}; do
  names=$(hosts_names_for "$a")
  if has_name "$names" "$FQDN" && has_name "$names" "$SHORT"; then
    self_hit=$a
    break
  fi
done

# Corroboration only, and it is corroboration that cannot be trusted on its own:
# nss-myhostname answers for the local hostname whether or not $HOSTS says
# anything, so this line would report success for a machine with an empty hosts
# file. timeout because a lookup that misses `files` is sent to DNS first (`hosts:
# files dns myhostname`), and a grader that hangs is worse than one that fails.
self_getent=$(timeout 15 getent hosts "$FQDN" 2>/dev/null | awk 'NR == 1 { print $1 }')
if [[ -n $self_hit ]]; then
  ck_pass self-hosts-entry "$HOSTS maps this host's own address to $FQDN and $SHORT" \
    "$HOSTS maps $self_hit to both names; getent resolves $FQDN to ${self_getent:-nothing}"
else
  ck_fail self-hosts-entry "$HOSTS maps this host's own address to $FQDN and $SHORT" \
    "no line in $HOSTS lists both $FQDN and $SHORT as names for ${addr_candidates[*]:-the address of this host} (interface ${LIVE_DEV:-unknown}, live address ${LIVE_ADDR:-none}, address at setup $STAMP_ADDR). Names for the live address today: $(names_summary "${LIVE_ADDR:-none}"). A hosts line is 'address name [alias...]', address first; and note that this host answers to its own name through nss-myhostname whether or not the file says so, so 'getent hosts $FQDN' succeeding is not evidence that the entry is there - it currently returns ${self_getent:-nothing}"
fi

# --- 4. the peer ----------------------------------------------------------
# Asked of the resolver, not of the file, because "resolves to" is the
# requirement and any of several correct hosts-file layouts satisfies it. Both
# names, and both must land on the right address: a student who mapped only the
# fully qualified name has not finished, and one who typed the columns the wrong
# way round (antisolutions/04) has an entry that resolves nothing.
peer_ok=yes
peer_detail=""
for n in "$PEER_FQDN" "$PEER_SHORT"; do
  got=$(timeout 15 getent hosts "$n" 2>/dev/null | awk 'NR == 1 { print $1 }')
  peer_detail+="$n -> ${got:-nothing}; "
  [[ $got == "$PEER_ADDR" ]] || peer_ok=no
done
if [[ $peer_ok == yes ]]; then
  ck_pass peer-resolves "$PEER_FQDN and $PEER_SHORT resolve to $PEER_ADDR" "${peer_detail%; }"
else
  ck_fail peer-resolves "$PEER_FQDN and $PEER_SHORT resolve to $PEER_ADDR" \
    "${peer_detail%; }. No name server on this network knows this name, so the answer has to come from $HOSTS, where a line reads 'address canonical-name [alias...]' - the address first, then every name it should answer to. Names currently listed for $PEER_ADDR: $(names_summary "$PEER_ADDR")"
fi

# --- 5 and 6. the resolver settings in the profile -----------------------
# The profile graded is the one setup.sh recorded, which is the one that was
# active on the only interface when the lab handed the machine over - "the
# connection profile that configures this host's interface", in the prompt's
# words. Keyed by UUID rather than by name: a name can contain a colon, which
# nmcli escapes and which breaks field splitting (the hazard
# troubleshooting/028's solutions/02 documents), and a UUID also survives the
# student renaming the profile.
#
# Read twice. nmcli's answer is NetworkManager's own view of the saved profile and
# is the primary witness. The keyfile is the second, and it is not redundant: it
# catches the student who edited the file correctly but has not reloaded, whose
# setting is genuinely on disk and genuinely applied at the next boot - which is
# what the checkpoint claims - even though nmcli's in-memory copy is still stale.
conn_dns=$(nmcli -g ipv4.dns connection show uuid "$STAMP_UUID" 2>/dev/null)
conn_search=$(nmcli -g ipv4.dns-search connection show uuid "$STAMP_UUID" 2>/dev/null)

keyfile=$(sudo nmcli -g UUID,FILENAME connection show 2>/dev/null |
  awk -F: -v u="$STAMP_UUID" '$1 == u && !seen { sub(/^[^:]*:/, ""); print; seen = 1 }')
key_dns=""
key_search=""
if [[ -n $keyfile ]] && sudo test -f "$keyfile"; then
  # One key out of the keyfile's [ipv4] section. Section-aware on purpose: `dns=`
  # also appears under [ipv6], and an IPv6 resolver is not what was asked for.
  key_val() {
    sudo awk -F= -v k="$1" '
      /^[[:space:]]*\[/ { sect = $0; next }
      sect ~ /^\[ipv4\]/ {
        key = $1
        gsub(/[[:space:]]/, "", key)
        if (key == k) { v = substr($0, index($0, "=") + 1); gsub(/^[[:space:]]+|[[:space:]]+$/, "", v) }
      }
      END { print v }' "$keyfile" 2>/dev/null
  }
  key_dns=$(key_val dns)
  key_search=$(key_val dns-search)
fi

# Is VALUE one of the entries in LIST, where nmcli separates entries with commas
# and the keyfile separates them with semicolons? Split on both, compared as whole
# entries: a substring test would accept 192.168.70.20 for 192.168.70.2, and
# accept notlab.example.com for lab.example.com.
has_entry() {
  printf '%s\n' "$1" | awk -v w="$2" '
    {
      gsub(/[;,]/, "\n")
      n = split($0, f, "\n")
      for (i = 1; i <= n; i++) {
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", f[i])
        if (f[i] == w) hit = 1
      }
    }
    END { exit hit ? 0 : 1 }'
}

# Read for the detail only, never as evidence. NetworkManager generates this file;
# a value that is here and not in the profile is a value the next activation
# deletes, which is precisely the mistake antisolutions/02 makes.
resolv_ns=$(awk '$1 == "nameserver" { printf "%s ", $2 }' "$RESOLV" 2>/dev/null)
resolv_search=$(awk '$1 == "search" || $1 == "domain" { for (i = 2; i <= NF; i++) printf "%s ", $i }' "$RESOLV" 2>/dev/null)
resolv_note="/etc/resolv.conf currently lists nameservers [${resolv_ns:-none}] and search domains [${resolv_search:-none}], but that file is generated by NetworkManager and rewritten whenever this connection activates, so what is in it is not what makes a setting persistent"

if has_entry "$conn_dns" "$DNS_SERVER" || has_entry "$key_dns" "$DNS_SERVER"; then
  ck_pass dns-nameserver "the connection profile records $DNS_SERVER as its DNS server" \
    "profile $STAMP_UUID has ipv4.dns='${conn_dns:-empty}'${keyfile:+, keyfile $keyfile has dns='${key_dns:-empty}'}"
else
  ck_fail dns-nameserver "the connection profile records $DNS_SERVER as its DNS server" \
    "profile $STAMP_UUID (device ${STAMP_DEV}) has ipv4.dns='${conn_dns:-empty}'${keyfile:+ and its keyfile $keyfile has dns='${key_dns:-empty}'}. $resolv_note"
fi

if has_entry "$conn_search" "$DNS_SEARCH" || has_entry "$key_search" "$DNS_SEARCH"; then
  ck_pass dns-search "the connection profile records $DNS_SEARCH as its DNS search domain" \
    "profile $STAMP_UUID has ipv4.dns-search='${conn_search:-empty}'${keyfile:+, keyfile $keyfile has dns-search='${key_search:-empty}'}"
else
  ck_fail dns-search "the connection profile records $DNS_SEARCH as its DNS search domain" \
    "profile $STAMP_UUID (device ${STAMP_DEV}) has ipv4.dns-search='${conn_search:-empty}'${keyfile:+ and its keyfile $keyfile has dns-search='${key_search:-empty}'}. $resolv_note"
fi

# --- 7. the localhost entries ---------------------------------------------
# An invariant, and a probed one: antisolutions/05 replaces $HOSTS wholesale
# instead of adding to it, which is the commonest way this file gets damaged and
# the reason the prompt says to leave those two lines alone. It is not a
# baseline-fail - a stock RHEL 9 /etc/hosts contains both lines and setup.sh
# proves they are there before the student starts.
#
# Worth knowing why the damage is survivable at all: nss-myhostname also answers
# `localhost`, so a guest with no hosts file still resolves it and stays
# reachable. That makes this a safe thing to break in a fixture and still a wrong
# thing to leave broken - nothing that reads the file directly, and nothing that
# runs before nsswitch is consulted, gets the same courtesy.
lo4=$(hosts_names_for 127.0.0.1)
lo6=$(hosts_names_for ::1)
if has_name "$lo4" localhost && has_name "$lo6" localhost; then
  ck_pass hosts-localhost "$HOSTS still maps 127.0.0.1 and ::1 to localhost"
else
  ck_fail hosts-localhost "$HOSTS still maps 127.0.0.1 and ::1 to localhost" \
    "127.0.0.1 currently names [$(printf '%s' "$lo4" | tr '\n' ' ')] and ::1 names [$(printf '%s' "$lo6" | tr '\n' ' ')]. Both stock lines should still be there: add your entries to $HOSTS rather than replacing what is in it"
fi

# --- 8. the network this task must not disturb ---------------------------
# Three facts, all compared against what setup.sh recorded rather than against a
# hardcoded expectation, so a lab re-pointed at a static address or a differently
# named interface still grades correctly. Fails closed: an empty read is a
# failure, not a match.
net_why=""
[[ -n $LIVE_DEV && -n $LIVE_ADDR ]] \
  || net_why+="no non-loopback interface carries a global IPv4 address (setup saw $STAMP_DEV with $STAMP_ADDR); "
[[ -z $LIVE_DEV || $LIVE_DEV == "$STAMP_DEV" ]] \
  || net_why+="the interface carrying the address is now $LIVE_DEV, not $STAMP_DEV; "
live_uuid=$(nmcli -g UUID,DEVICE connection show --active 2>/dev/null |
  awk -F: -v d="$STAMP_DEV" '$2 == d && !seen { print $1; seen = 1 }')
[[ $live_uuid == "$STAMP_UUID" ]] \
  || net_why+="the connection active on $STAMP_DEV is now '${live_uuid:-nothing}', not the profile the lab handed over ($STAMP_UUID); "
live_method=$(nmcli -g ipv4.method connection show uuid "$STAMP_UUID" 2>/dev/null)
[[ $live_method == "$STAMP_METHOD" ]] \
  || net_why+="ipv4.method on that profile is now '${live_method:-unreadable}', not '$STAMP_METHOD'; "

if [[ -z $net_why ]]; then
  ck_pass network-intact "the interface, its address and its connection profile are unchanged" \
    "$STAMP_DEV holds $LIVE_ADDR, profile $STAMP_UUID is active on it, ipv4.method=$live_method"
else
  ck_fail network-intact "the interface, its address and its connection profile are unchanged" \
    "${net_why%; }. This task is about names, not addressing: recording a DNS server in a profile needs no change to the address, the gateway, ipv4.method or the connection's state"
fi

exit 0
